name: Development branch actions

# run when issued manually, push or pr on "develop"
on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths-ignore:
      - "**.md"
      - "**.txt"
  pull_request:
    branches: [develop]
    paths-ignore:
      - "**.md"
      - "**.txt"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-node:
    uses: ./.github/workflows/test-node.yml
  test-deno:
    uses: ./.github/workflows/test-deno.yml
  test-bun:
    uses: ./.github/workflows/test-bun.yml

