name: Master branch actions

# run when issued manually, push or pr on "master"
on:
   workflow_dispatch:
   pull_request:
      branches: [master]
      paths-ignore:
         - '**.md'
         - '**.txt'
   push:
      branches: [master]
      paths-ignore:
         - '**.md'
         - '**.txt'

concurrency:
   group: '${{ github.workflow }} @ ${{ github.event.pull_request.number || github.ref }}'
   cancel-in-progress: true

jobs:
   test-node:
      uses: ./.github/workflows/test-node.yml
   test-deno:
      uses: ./.github/workflows/test-deno.yml
   test-bun:
      uses: ./.github/workflows/test-bun.yml
